
# step 1
FROM node:18 AS build

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build --prod

#step 2
FROM nginx:alpine

COPY --from=build /app/dist/angular-project /usr/share/nginx/html

COPY nginx.conf /etc/nginx/nginx.conf
